#!/usr/bin/env python3
"""Regenerate src/io/formats/html_viewer_resources.hpp from the editable
viewer resources under src/visualizer/gui/resources/viewer/.

The exported self-contained HTML viewer inlines a PlayCanvas-based app
(viewer_template.html + index.css + index.js) plus a vendored translate
gizmo (gizmo.js) and a custom measurement tool (measure-tool.js). Since
MSVC caps individual string literals at 16380 characters, each resource is
emitted as a sequence of adjacent raw-string literals that the compiler
concatenates automatically.

Usage:
    python tools/generate_html_viewer_resources.py

Run this after editing any file under src/visualizer/gui/resources/viewer/.
Do not hand-edit the generated html_viewer_resources.hpp file.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VIEWER_DIR = REPO_ROOT / "src" / "visualizer" / "gui" / "resources" / "viewer"
OUTPUT_PATH = REPO_ROOT / "src" / "io" / "formats" / "html_viewer_resources.hpp"

# Stay comfortably under MSVC's 16380-character raw string literal limit.
CHUNK_SIZE = 16000

MAIN_MARKER = "const main = (app, camera, settingsJson, config) => {"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_trailing_export(js: str, export_line_re: str) -> str:
    """Remove a trailing `export { ... };` line (and any blank line before it)."""
    pattern = re.compile(export_line_re + r"\s*\Z", re.MULTILINE)
    stripped, count = pattern.subn("", js.rstrip() + "\n")
    if count != 1:
        raise RuntimeError(f"Expected exactly one trailing export statement matching {export_line_re!r}, found {count}")
    return stripped.rstrip("\n")


def build_measure_tool_block(gizmo_js: str, measure_tool_js: str) -> str:
    gizmo_body = strip_trailing_export(gizmo_js, r"^export \{ Gizmo, TranslateGizmo \};$")
    lines = [
        "// ---- BEGIN vendored measurement tool (see gizmo.js / measure-tool.js) ----",
        "// AUTO-GENERATED: do not edit index.js directly here; edit gizmo.js / measure-tool.js instead.",
        "let __lfsInitMeasureTool;",
        "{",
        gizmo_body,
        "",
        measure_tool_js.rstrip("\n"),
        "",
        "    __lfsInitMeasureTool = initMeasureTool;",
        "}",
        "// ---- END vendored measurement tool ----",
        "",
        "",
    ]
    return "\n".join(lines)


def build_index_js(index_js: str, gizmo_js: str, measure_tool_js: str) -> str:
    if MAIN_MARKER not in index_js:
        raise RuntimeError(f"Could not find insertion marker in index.js: {MAIN_MARKER!r}")
    block = build_measure_tool_block(gizmo_js, measure_tool_js)
    return index_js.replace(MAIN_MARKER, block + MAIN_MARKER, 1)


def chunk_text(text: str, chunk_size: int) -> list:
    return [text[i:i + chunk_size] for i in range(0, len(text), chunk_size)] or [""]


def raw_string_literal(chunk: str, tag: str) -> str:
    closing = f"){tag}\""
    if closing in chunk:
        raise RuntimeError(f"Chunk contains raw-string delimiter collision for tag {tag!r}; pick a different prefix")
    return f"R\"{tag}({chunk}){tag}\""


def emit_chunks(text: str, prefix: str) -> str:
    chunks = chunk_text(text, CHUNK_SIZE)
    literals = [raw_string_literal(chunk, f"{prefix}{i}") for i, chunk in enumerate(chunks)]
    return "\n            ".join(literals)


def generate_header(template_html: str, css: str, js: str) -> str:
    tmpl_literal = emit_chunks(template_html, "TMPL")
    css_literal = emit_chunks(css, "CSS")
    js_literal = emit_chunks(js, "JS")

    return f"""/* SPDX-FileCopyrightText: 2025 LichtFeld Studio Authors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/generate_html_viewer_resources.py from:
 *   src/visualizer/gui/resources/viewer/viewer_template.html
 *   src/visualizer/gui/resources/viewer/index.css
 *   src/visualizer/gui/resources/viewer/index.js
 *   src/visualizer/gui/resources/viewer/gizmo.js
 *   src/visualizer/gui/resources/viewer/measure-tool.js
 * Strings are chunked for MSVC compatibility (16380 char limit)
 */

#pragma once

#include <string>

namespace lfs::io {{

    inline const std::string& get_viewer_template() {{
        static const std::string tmpl =
            {tmpl_literal};
        return tmpl;
    }}

    inline const std::string& get_viewer_css() {{
        static const std::string css = {css_literal};
        return css;
    }}

    inline const std::string& get_viewer_js() {{
        static const std::string js =
            {js_literal};
        return js;
    }}

}} // namespace lfs::io
"""


def main() -> int:
    template_html = read(VIEWER_DIR / "viewer_template.html")
    css = read(VIEWER_DIR / "index.css")
    index_js = read(VIEWER_DIR / "index.js")
    gizmo_js = read(VIEWER_DIR / "gizmo.js")
    measure_tool_js = read(VIEWER_DIR / "measure-tool.js")

    js = build_index_js(index_js, gizmo_js, measure_tool_js)

    header = generate_header(template_html, css, js)
    OUTPUT_PATH.write_text(header, encoding="utf-8", newline="\n")

    print(f"Wrote {OUTPUT_PATH} ({len(header)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
