# SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
# SPDX-License-Identifier: GPL-3.0-or-later
find_package(nlohmann_json CONFIG REQUIRED)
find_package(OpenEXR 3.4.15 CONFIG REQUIRED)
find_package(JPEG REQUIRED)
find_package(PNG REQUIRED)
find_package(ZLIB REQUIRED)
find_package(TIFF REQUIRED)
find_package(Threads REQUIRED)
find_package(WebP CONFIG QUIET)
if(NOT TARGET WebP::webp)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(LFS_MEDIA_WEBP REQUIRED IMPORTED_TARGET libwebp)
    add_library(WebP::webp ALIAS PkgConfig::LFS_MEDIA_WEBP)
endif()
if(NOT TARGET LichtFeldMedia::ffmpeg)
    if(DEFINED VCPKG_TARGET_TRIPLET)
        find_package(FFMPEG REQUIRED)
        set(_lfs_media_ffmpeg_include ${FFMPEG_INCLUDE_DIRS})
        set(_lfs_media_ffmpeg_libraries ${FFMPEG_LIBRARIES})
    else()
        find_path(_lfs_media_ffmpeg_include libavformat/avformat.h REQUIRED)
        foreach(_component avformat avcodec avutil swscale)
            find_library(_lfs_media_${_component} NAMES ${_component} REQUIRED)
            list(APPEND _lfs_media_ffmpeg_libraries ${_lfs_media_${_component}})
        endforeach()
    endif()
    add_library(LichtFeldMedia::ffmpeg INTERFACE IMPORTED GLOBAL)
    set_target_properties(LichtFeldMedia::ffmpeg PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_lfs_media_ffmpeg_include}"
        INTERFACE_LINK_LIBRARIES "${_lfs_media_ffmpeg_libraries}")
endif()
