name: Clang Format Check

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Print clang-format version
        run: |
          clang-format --version

      - name: Run clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|c\|h\|cu\|cuh\)' \
            -exec clang-format -i {} +

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Apply clang-format"
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
          else
            echo "No formatting changes needed."
          fi
